baseURL = 'https://flex.sys-adm.in/'
languageCode = 'en-us'
title = 'Flex App Additions Methodology'
theme = "ace-doc"

[params]

    # toc = false
    disableSearch = true
    disableReadmoreNav = true